on:
  push:
    branches:
      - master    




jobs:
  build:
    runs-on: ubuntu-latest
 

    steps:
      - name: 'printing folder contents 1'
        run: ls


      - uses: actions/checkout@v3

      - name: 'printing folder contents 2'
        run: ls
      
      - name: "login to docker hub"
        run: docker login --username mohamednower --password 123456MM7815
        






